{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "app-secret-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "file-storage-external-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "kafka-sasl-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "kafka-sasl-username"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "rabbitmq-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "redis-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "access-mode"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-enabled"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "document-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "document-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "document-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_backend.secretName }}
      type: Opaque
      data:
        - objectName: "api-key"
          key: api-key
        - objectName: "app-secret-key"
          key: app-secret-key
        - objectName: "file-storage-external-url"
          key: file-storage-external-url
        - objectName: "kafka-sasl-password"
          key: kafka-sasl-password
        - objectName: "kafka-sasl-username"
          key: kafka-sasl-username
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
        - objectName: "rabbitmq-password"
          key: rabbitmq-password
        - objectName: "redis-password"
          key: redis-password
        - objectName: "access-mode"
          key: access-mode
        - objectName: "auth-enabled"
          key: auth-enabled
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "document-db-password"
          key: document-db-password
        - objectName: "document-db-user"
          key: document-db-user
        - objectName: "db-host"
          key: db-host
        - objectName: "document-db"
          key: document-db
{{- end }}