# Default values for deps-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Secrets declaration
# Precreate them before deploy
# kubectl create secret generic app-secret-key --from-literal=app-secret-key='<APP_SECRET_KEY>'
# kubectl create secret generic database-host --from-literal=database-host='<DATABASE_HOST>'
# kubectl create secret generic database-user-secret --from-literal=database-user-secret='<database-user-password>'
# kubectl create secret generic database-work-user-secret --from-literal=database-work-user-secret='<database-work-user-secret>'
# kubectl create secret generic file-storage-external-url --from-literal=file-storage-external-url='<https://FRONTEND_URL/api/storage/v1/file>'
# kubectl create secret generic keycloak-certs-endpoint --from-literal=keycloak-certs-endpoint='<https://KEYCLOAK_URL/auth/realms/Test/protocol/openid-connect/certs>'
secrets:
  app_secret_key:
    secretName: app-secret-key
  file_storage_external_url:
    secretName: file-storage-external-url
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  redis_password:
    secretName: redis-password
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  kafka_secrets:
    secretName: kafka-secrets
  api_key:
    secretName: api-key
  common_secret:
    secretName: common-secret
  database_ssl_secret:
    secretName: database-ssl-secret
  deps_backend:
    secretName: deps-backend
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    repository: ""
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

backend:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-document-api"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
#    limits:
#      cpu: 300m
#      memory: 900Mi
#    requests:
#      cpu: 100m
#      memory: 450Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

document_consumer:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-document-api"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
#    limits:
#      cpu: 100m
#      memory: 850Mi
#    requests:
#      cpu: 80m
#      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

migrator_update:
  image:
    path: "/deps-dev-x01/deps-document-api-migrator"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

migrator_fixtures:
  image:
    path: "/deps-dev-x01/deps-document-api-migrator"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  
  database_sslcerts_path: "/home/dbcerts"


backend_settings:
  SECRET_KEY: test
  ENV: dev
  # File Blob storage service
  FILE_STORAGE_MEDIA_ROOT: '/media/files/'
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000'

  OBJECT_STORAGE_MODE: "sync"
  OBJECT_STORAGE_TYPE: "file-storage"

  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com

  GCP_BLOB_STORAGE_BUCKET_NAME: ""

  # Validation service
  VALIDATION_API_URL: 'http://validation:8005'
  # Auth
  AUTH_VERIFY_SSL: 'false'
  CREATE_ROLE: deps-creator
  READ_ROLE: deps-reader
  WRITE_ROLE: deps-writer
  TEST_CLIENT_ID: TEST
  TEST_CLIENT_SECRET: TEST
  TEST_API_BASE_URL: TEST
  TEST_ACCESS_TOKEN_URL: TEST
  TEST_AUTHORIZE_URL: TEST
  REVIEWER_REASSIGN_ENABLED: 'false'
  # PostgreSQL
  DATABASE_PORT: '5432'
  DATABASE_DIALECT: postgresql
  DATABASE_DRIVER: psycopg2
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"
  # Redis
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 0
  # Priority (seconds)
  PRIORITY_MEDIUM_BOUNDARY: '3600'
  PRIORITY_HIGH_BOUNDARY: '10800'
  # Corleone
  CORLEONE_API_HOST: corleone
  CORLEONE_API_PORT: '8000'
  CORLEONE_API_ENDPOINT: '/api/corleone/v1'

  LOG_LEVEL: "INFO"
  PARSING_ENABLED: 'true'
  DOCUMENTATION_ENABLED: 'true'

  # RabitMQ
  RABBITMQ_TLS_ENABLED: false
  RABBITMQ_TLS_DLX_PER_QUEUE: false
  RABBITMQ_TLS_CONSUMER_STRATEGY: 'AVAILABILITY'

  KAFKA_GROUP_ID: documents
  KAFKA_SECURITY_ENABLED: false

  # Auto validation
  AUTO_VALIDATION_ENABLED: 'false'

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic' 
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-documents
  EXPORTER_TYPE: azure

migration_settings:
  DATABASE_PORT: '5432'
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000'

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-backend
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev' 

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

secret_project_id:
  id: ""

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

# Enabled vault settings means that secrets are pulled from hashicorp vault server. Turn off this setting by changing true to false if you are using this repo in another project. If you haven't integrated your cluster with vault deploy won't work.
vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

vault_enabled_backend:
  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: app-secret-key
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: db-host
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db-password
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db-user
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db
    - name: FILE_STORAGE_EXTERNAL_URL
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: file-storage-external-url
    - name: AZURE_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: aws-secret-access-key
    - name: S3_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: aws-storage-s3-endpoint-url
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: aws-storage-s3-bucket-name
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: deps-parsing
          key: gcp-api-key
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: keycloak-certs-endpoint
    - name: AUTH_ENABLED
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: auth-enabled
    - name: ACCESS_MODE
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: access-mode
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: message-broker-connection-string
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: redis-password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: api-key

vault_disabled_backend:
  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret-key
          key: app-secret-key
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: database-host
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: password
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: user
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: database-db
    - name: FILE_STORAGE_EXTERNAL_URL
      valueFrom:
        secretKeyRef:
          name: file-storage-external-url
          key: file-storage-external-url
    - name: AZURE_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-connection-string
    - name: AZURE_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: azure-blob-storage
          key: azure-container-name
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: file-storage-aws-credentials
          key: aws-secret-access-key
    - name: GCP_BLOB_STORAGE_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: gcp-credentials
          key: gcp-api-key
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: keycloak-certs-endpoint
          key: keycloak-certs-endpoint
    - name: AUTH_ENABLED
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: auth-enabled
    - name: ACCESS_MODE
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: access-mode
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-connection-string
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: redis-password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: api-key

vault_enabled_consumer:
  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: app-secret-key
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: db-host
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db-password
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db-user
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: document-db
    - name: FILE_STORAGE_EXTERNAL_URL
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: file-storage-external-url
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: keycloak-certs-endpoint
    - name: AUTH_ENABLED
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: auth-enabled
    - name: ACCESS_MODE
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: access-mode
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: message-broker-connection-string
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: deps-backend
          key: api-key

vault_disabled_consumer:
  env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret-key
          key: app-secret-key
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: database-host
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: password
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: user
    - name: DATABASE_DB
      valueFrom:
        secretKeyRef:
          name: deps-database
          key: database-db
    - name: FILE_STORAGE_EXTERNAL_URL
      valueFrom:
        secretKeyRef:
          name: file-storage-external-url
          key: file-storage-external-url
    - name: AUTH_CERTS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: keycloak-certs-endpoint
          key: keycloak-certs-endpoint
    - name: AUTH_ENABLED
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: auth-enabled
    - name: ACCESS_MODE
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: access-mode
    - name: MESSAGING_DRIVER
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-driver
    - name: MESSAGE_BROKER_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: common-secret
          key: message-broker-connection-string
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-key
          key: api-key
