from .analytics import AnalyticsRepository
from .batch_upload_data import BatchUploadDataRepository
from .comment import CommentRepository
from .document import DocumentEntityRepository
from .document_log import DocumentLogEntityRepository
from .document_type import DocumentTypeRepository
from .group import GroupRepository
from .label import LabelRepository
from .relation import RelationRepository
