version: "3.4"

services:
  api:
    image: "document-api-dev"
    container_name: deps-document-api

  document-consumer:
    image: "document-api-dev"
    container_name: deps-document-consumer
    command: python -m deps_documents consume

  migrator:
    image: "document-api-migrator"
    container_name: deps-document-api-migrator

  fixtures:
    image: "document-api-migrator"
    container_name: deps-document-fixtures

networks:
  deps-network:
    external: true
