apiVersion: v1
kind: ConfigMap
metadata:
  name: migrator-configmap
  labels:
    {{- include "deps-backend-migrator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
data:
    DATABASE_PORT: '{{ .Values.migration_settings.DATABASE_PORT }}'
    FILE_STORAGE_URL: '{{ .Values.migration_settings.FILE_STORAGE_URL }}'
    {{ if .Values.migration_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
    DATABASE_SSLKEY: {{ .Values.migration_settings.DATABASE_SSLKEY_PATH }}
    DATABASE_SSLCERT: {{ .Values.migration_settings.DATABASE_SSLCERT_PATH }}
    DATABASE_SSLROOTCERT: {{ .Values.migration_settings.DATABASE_SSLROOTCERT_PATH }}
    {{ end }}
    
