backend:
  image:
    path: "/deps-platform/deps-document-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:


document_consumer:
  image:
    path: "/deps-platform/deps-document-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

migrator_update:
  image:
    path: "/deps-platform/deps-document-api-migrator"

migrator_fixtures:
  image:
    path: "/deps-platform/deps-document-api-migrator"

backend_settings:
  ENV: staging
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  LOG_LEVEL: "INFO"

  OBJECT_STORAGE_TYPE: aws
  S3_BUCKET_NAME : bucket_name
  S3_ENDPOINT_URL : https://s3.eu-central-1.amazonaws.com

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

helm: 
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-staging'
  roleName: 'k8s-staging'
  vaultKubernetesMountPath: 'kubernetes-staging'

service_account:
  serviceAccountName: 'deps-staging'

