helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
  resources: {}

backend:
  image:
    path: "/deps-platform/deps-document-api"
  resources: {}

document_consumer:
  image:
    path: "/deps-platform/deps-document-api"
  resources: {}

migrator_update:
  image:
    path: "/deps-platform/deps-document-api-migrator"

migrator_fixtures:
  image:
    path: "/deps-platform/deps-document-api-migrator"

backend_settings:
  ENV: other
  # PostgreSQL
  DATABASE_PORT: '5432'
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  LOG_LEVEL: "INFO"

migration_settings:
  DATABASE_PORT: '5432'
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  FILE_STORAGE_URL: 'http://file-storage-nginx:8000'

helm: 
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-other'
  roleName: 'k8s-other'
  vaultKubernetesMountPath: 'kubernetes-other'

service_account:
  serviceAccountName: 'deps-other'

